[target.'cfg(all(target_arch = "arm", target_os = "none"))']
rustflags = [
    "-Clink-arg=-Timxrt-link.x",
    "-Clink-arg=-Tdefmt.x",
    "-Clink-arg=-Tdevice.x",
    "-Clink-arg=-error-limit=0",
    "-Clink-arg=-nmagic",
]
