[build]
target = "thumbv7em-none-eabihf"
target-dir = "target/imxrt1170evk-cm7"

[target.thumbv7em-none-eabihf]
runner = "probe-rs run --chip=mimxrt1170"
rustflags = ["-Ctarget-cpu=cortex-m7"]

[profile.dev]
opt-level = 1
panic = "abort"
